<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaEstoque.API\SistemaEstoque.API.csproj" />
    <ProjectReference Include="..\SistemaEstoque.Domain\SistemaEstoque.Domain.csproj" />
    <ProjectReference Include="..\SistemaEstoque.Infrastructure\SistemaEstoque.Infrastructure.csproj" />
  </ItemGroup>

</Project>
